/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MapRouteImport } from './routes/map'
import { Route as LostFoundRouteImport } from './routes/lost-found'
import { Route as FaresRouteImport } from './routes/fares'
import { Route as CrowdingRouteImport } from './routes/crowding'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LostFoundRoute = LostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => rootRouteImport,
} as any)
const FaresRoute = FaresRouteImport.update({
  id: '/fares',
  path: '/fares',
  getParentRoute: () => rootRouteImport,
} as any)
const CrowdingRoute = CrowdingRouteImport.update({
  id: '/crowding',
  path: '/crowding',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/crowding': typeof CrowdingRoute
  '/fares': typeof FaresRoute
  '/lost-found': typeof LostFoundRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/planner': typeof PlannerRoute
  '/register': typeof RegisterRoute
  '/safety': typeof SafetyRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/tickets': typeof TicketsRoute
  '/tracking': typeof TrackingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/crowding': typeof CrowdingRoute
  '/fares': typeof FaresRoute
  '/lost-found': typeof LostFoundRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/planner': typeof PlannerRoute
  '/register': typeof RegisterRoute
  '/safety': typeof SafetyRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/tickets': typeof TicketsRoute
  '/tracking': typeof TrackingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/crowding': typeof CrowdingRoute
  '/fares': typeof FaresRoute
  '/lost-found': typeof LostFoundRoute
  '/map': typeof MapRoute
  '/news': typeof NewsRoute
  '/planner': typeof PlannerRoute
  '/register': typeof RegisterRoute
  '/safety': typeof SafetyRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/tickets': typeof TicketsRoute
  '/tracking': typeof TrackingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/crowding'
    | '/fares'
    | '/lost-found'
    | '/map'
    | '/news'
    | '/planner'
    | '/register'
    | '/safety'
    | '/saved'
    | '/search'
    | '/tickets'
    | '/tracking'
    | '/admin/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/crowding'
    | '/fares'
    | '/lost-found'
    | '/map'
    | '/news'
    | '/planner'
    | '/register'
    | '/safety'
    | '/saved'
    | '/search'
    | '/tickets'
    | '/tracking'
    | '/admin/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/crowding'
    | '/fares'
    | '/lost-found'
    | '/map'
    | '/news'
    | '/planner'
    | '/register'
    | '/safety'
    | '/saved'
    | '/search'
    | '/tickets'
    | '/tracking'
    | '/admin/login'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  CrowdingRoute: typeof CrowdingRoute
  FaresRoute: typeof FaresRoute
  LostFoundRoute: typeof LostFoundRoute
  MapRoute: typeof MapRoute
  NewsRoute: typeof NewsRoute
  PlannerRoute: typeof PlannerRoute
  RegisterRoute: typeof RegisterRoute
  SafetyRoute: typeof SafetyRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  TicketsRoute: typeof TicketsRoute
  TrackingRoute: typeof TrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost-found': {
      id: '/lost-found'
      path: '/lost-found'
      fullPath: '/lost-found'
      preLoaderRoute: typeof LostFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fares': {
      id: '/fares'
      path: '/fares'
      fullPath: '/fares'
      preLoaderRoute: typeof FaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crowding': {
      id: '/crowding'
      path: '/crowding'
      fullPath: '/crowding'
      preLoaderRoute: typeof CrowdingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlertsRoute: AlertsRoute,
  CrowdingRoute: CrowdingRoute,
  FaresRoute: FaresRoute,
  LostFoundRoute: LostFoundRoute,
  MapRoute: MapRoute,
  NewsRoute: NewsRoute,
  PlannerRoute: PlannerRoute,
  RegisterRoute: RegisterRoute,
  SafetyRoute: SafetyRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  TicketsRoute: TicketsRoute,
  TrackingRoute: TrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
